### PR TITLE
Single table support

### PR DESCRIPTION
**Pull request by famence**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
—

## What is the new behavior?
Added the DynamooseModule.forTable provider and InjectTable decorator in order to utilise the DynamoDB's single table approach with following usage:
```
DynamooseModule.forTable({
  name: 'pets',
  models: [{
    name: 'Cat',
    schema: CatSchema,
  }, {
    name: 'Dog',
    schema: DogSchema,
  }],
})

...

export class PetService {
  constructor(
    @InjectTable('pets')
    private petsTable: Table,
  ) {}
}
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by hardyscc** [comment]
@famence Could you let me know what is use case for that,  as I know model also support multi schemas, which can be use for single table approach as well, please see https://github.com/hardyscc/nestjs-dynamoose/issues/291#issuecomment-981773701

**Comment by famence** [comment]
@hardyscc the main goal is to define a table imperatively and to be able to @InjectTable. The second thing is to use the Model as intended by dynamoose while still be able to utilise the single-table approach.

**Comment by hardyscc** [comment]
Currently, I am not considering supporting it as it is a bit confusing for the intended purpose. I will revisit this later when I have more time.

**Comment by nicholas-weidmann** [comment]
@famence 0.5.2 now makes this possible! A tablename can now be defined.
See https://github.com/hardyscc/nestjs-dynamoose/commit/d3cedbd01aa30a02872c7657312960d9ce0f0a2f

Thanks for the addition @hardyscc, before I had to do an ugly workaround with prefixes.

**Pull request closed without merging**
