### PR TITLE
feat: add serializers support

### PR DESCRIPTION
**Pull request by hardyscc**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #236 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Review by andrewda — APPROVED** [review]
Looks good, thank you! :+1:

**Comment by hardyscc** [comment]
@andrewda just created a beta build, would u mind to have a test?

Please install this beta by
```
npm install nestjs-dynamoose@beta
```

**Comment by andrewda** [comment]
@hardyscc Looks good! I think there are just a few typing updates that need to be fixed though. Specifically, documents should have a [`.serialize()` method](https://dynamoosejs.com/guide/Document/#documentserializeserializer). For example, the following code works, but needs a `// @ts-ignore` to compile:


```ts
    const user = await this.userModel.get({ id: '123' });

    // @ts-ignore
    const serialized = user.serialize('frontend');

    console.log(serialized);
```

It probably also makes sense to implement the [`.populate()` method](https://dynamoosejs.com/guide/Document/#documentpopulatesettings-callback) too.

**Comment by hardyscc** [comment]
@andrewda since the object interface don't need to extends document in my design, I suggest to do it this way, is it ok for u?

```
    const user = await this.userModel.get({ id: '123' });

    const serialized = this.userModel.serialize(user, 'frontend');

    console.log(serialized);
```

**Comment by hardyscc** [comment]
@andrewda it is done, please retry the beta again thanks.

**Comment by andrewda** [comment]
Looks mostly good, though this might be a breaking change for some users because of the type change from `Data` to `Document<Data>`.

**Comment by hardyscc** [comment]
@andrewda no worries, this is not a breaking changes as
```ts
type Documet<T> = T & { serialize(...) }
```

**Pull request merged**
