### PR TITLE
feat: add option to add custom provider

### PR DESCRIPTION
**Pull request by razin99**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
Add feature to allow a user to use a custom provider token.

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

The table name itself is exposed as a provider

Issue Number: N/A

## What is the new behavior?
The provider token is used if its defined, otherwise, fallback to default behaviour

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by hardyscc** [comment]
@razin99 Could you let me know the reason of changing it?

**Comment by hardyscc** [comment]
@razin99 Could you let me know the reason of changing it?

**Comment by razin99** [comment]
> @razin99 Could you let me know the reason of changing it?

Yeah sure, I wanted to use table names passed in from environment variables, but at the same time I want to keep all my injection tokens. That way I don't have to do: `InjectModel(process.env.SOME_TABLE)`

This change is not really a necessity, more of a 'nice-to-have' kind of change.

**Comment by hardyscc** [comment]
@razin99 ok i see, i will merge and release it later.

**Comment by andrewda** [comment]
Not sure I totally see the need for this. Wouldn't something like this be pretty much equivalent to what you're trying to do?

```ts
// cat.model.ts

export interface CatKey {
  id: string;
}

export interface Cat extends CatKey {
  name: string;
  color: number;
}

export type CatModel = Model<Cat, CatKey>;

export const CatModel: ModelDefinition = {
  name: process.env.CAT_TABLE,
  schema: new Schema({
    id: { type: String, hashKey: true },

    name: String,
    color: Number,
  }),
};
```

```ts
// cat.module.ts

@Module({
  imports: [DynamooseModule.forFeature([CatModel])],
  providers: [CatService],
})
export class CatModule {}
```

```ts
// cat.service.ts

@Injectable()
export class CatService {
  constructor(
    @InjectModel(CatModel.name) private catModel: CatModel,
  ) {}
}
```

**Comment by razin99** [comment]
Thanks @andrewda and @hardyscc this approach does fit my needs. Very clean solution!

**Pull request closed without merging**
