### PR TITLE
Query.exists() was missing

### PR DESCRIPTION
**Pull request by MickL**
https://github.com/dynamoosejs/dynamoose/blob/master/docs/api/Condition.md#conditionexists

### CODE REVIEW

**Comment by MickL** [comment]
Maybe this was null()

**Comment by hardyscc** [comment]
let's add a label to indicate this is belong to new Condition API

**Comment by MickL** [comment]
Isnt this library v2 only?

**Comment by MickL** [comment]
Could you please publish to npm?

**Comment by hardyscc** [comment]
can you temporary use `// @ts-ignore`, let's accumulate more fixes first, don't want to publish too frequently

**Comment by MickL** [comment]
I dont know if there are more coming... Im just working with this library. Maybe someone else comes in the meantime and wants to work and then he gets errors for no reason.

**Comment by hardyscc** [comment]
no worries, i will publish it for every few days

**Comment by hardyscc** [comment]
this type file is directly copy from v1 with small changes to fulfils my need.

**Comment by MickL** [comment]
But the library uses v2 so it should reflect v2. In the end, actually this file should be part of dynamoose instead but it seams like fishcharlie wants to go full TypeScript anyway.

**Comment by hardyscc** [comment]
yes that why I don't want to put too much effort on it. just temporary maintains here.

**Pull request merged**
